Hands-On Lab Task :
 1- Load a CSV dataset into a DataFrame and report its shape, columns, and dtypes.
 2- Count missing values per column and handle them (fill or drop) with a documented justification.
 3- Filter the data to a meaningful subset (e.g. rows above a threshold) and describe what you find.
 4- Use groupby to compute an aggregate statistic per category and interpret the result in a 
Markdown cell.

The dataset used is fifa_world_cup_2026_player_performance from the website "kaggle"

In [1]:
import pandas as pd

Task 1:

In [2]:
df = pd.read_csv('fifa_world_cup_2026_player_performance.csv')

In [5]:
print(df.shape)
print("--------------------------------")
print(df.info())

(54600, 75)
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB
None

Task 2:

In [14]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

This data set didnt have any null fields, but in another case where there would be i choose to drop becuase in this case a player with missing data isnt significant or important.

In [15]:
df.dropna(inplace=True)

In [49]:
df.drop_duplicates(inplace=True) # drop duplicate rows

Task 3:

This one lists the name, team and pass_accuracy of all worldCup players with pass accuracy more than 94%

In [23]:
df[df["pass_accuracy"] >= 0.94][["player_name", "team", "pass_accuracy"]]

             player_name     team  pass_accuracy
5              Dani Gavi    Spain           0.94
57      Christian Valera     Peru           0.95
111         Hakim Aguerd  Morocco           0.95
140         Ferland Seck  Senegal           0.95
185      Sandro Scamacca    Italy           0.96
...                  ...      ...            ...
54477     Kalidou Diallo  Senegal           0.96
54481       Sadio Diatta  Senegal           0.94
54483  Edouard Koulibaly  Senegal           0.94
54580  Mohannad Al-Amiri     Iraq           0.96
54584        Ali Mohanad     Iraq           0.96

[1517 rows x 3 columns]

This one is more specific:
    it lists player's name, team, pass accuracy, shots on target , goal and club name.
    based on the following:
    team is england.
    played more than 60 minutes.
    their pass accuracy is more than 85%.
    if they play for either of Real Madrid, Barcelona or Manchester United.

In [50]:
df[(df["team"] == "England") & (df["minutes_played"] > 60) & (df["pass_accuracy"] > 0.85) & ( ( df["club_name"] == "Real Madrid") | (df["club_name"] == "Barcelona") | (df["club_name"] == "Manchester United" ))] [["player_name", "team", "pass_accuracy", "shots_on_target", "goals", "club_name"]]

,player_name,team,pass_accuracy,shots_on_target,goals,club_name
2688,Kyle Gallagher,England,0.88,0,0,Manchester United
21687,Phil Walker,England,0.87,0,0,Barcelona
28818,Phil Walker,England,0.87,0,0,Barcelona
29071,Kyle Gallagher,England,0.88,0,0,Manchester United
31229,Phil Walker,England,0.87,0,0,Barcelona
42207,Kyle Gallagher,England,0.86,0,0,Manchester United
43140,Phil Walker,England,0.86,0,0,Barcelona
46024,Kyle Gallagher,England,0.87,0,0,Manchester United
50866,Phil Walker,England,0.91,0,0,Barcelona
51073,Phil Walker,England,0.88,0,0,Barcelona

Task 4:

This list the mean of tackles, interceptions, clearances and blocks grouped by position.

In [56]:
df.groupby("position").agg({"tackles": "mean" , "interceptions": "mean", "clearances": "mean", "blocks": "mean"}).sort_values(by="tackles", ascending=False)

             tackles  interceptions  clearances    blocks
position
Defender    1.309947       1.078730    1.739894  0.411217
Midfielder  0.885714       0.647024    0.420357  0.209345
Forward     0.332302       0.170000    0.124286  0.086032
Goalkeeper  0.000000       0.134762    0.419365  0.000000

This one list expected-goals, assistes and shots on target grouped by teams. (it might not be real life accurate but it is accurate to the dataSet)

In [61]:
df.groupby("team").agg({"expected_goals_xg": "sum", "assists": "sum", "shots_on_target": "sum"}).sort_values(by="expected_goals_xg", ascending=False)

               expected_goals_xg  assists  shots_on_target
team
Qatar                      31.18       93               69
Belgium                    27.41       68               88
Morocco                    25.47       61               88
Saudi Arabia               25.07       68               76
Scotland                   23.93       73               67
Cameroon                   23.25       66               80
Peru                       22.88       69               59
Australia                  22.34       64               65
Netherlands                22.30       85               95
Croatia                    22.10       70               50
Iran                       21.33       70               64
Turkey                     21.26       59               64
England                    20.99       58               50
Spain                      20.93       71               53
Denmark                    20.87       65               50
Jamaica                    20.70       80               67
Panama                     20.62       81               73
Costa Rica                 20.30       61               56
Canada                     20.10       61               47
Brazil                     19.34       52               55
Iraq                       19.33       56               61
Switzerland                18.70       42               49
Colombia                   18.68       52               42
Ghana                      17.91       65               65
Italy                      17.75       76               64
Uruguay                    17.40       48               45
Algeria                    17.32       52               55
Portugal                   16.75       54               52
Serbia                     16.58       62               38
Uzbekistan                 16.44       60               47
Austria                    16.31       44               49
Egypt                      16.27       54               44
Argentina                  16.04       57               53
Nigeria                    15.24       64               44
Poland                     15.13       49               51
Ecuador                    14.49       53               35
United States              14.09       61               45
Mexico                     13.97       59               65
Ukraine                    13.74       46               38
Tunisia                    13.63       48               42
Chile                      13.50       52               40
Japan                      13.33       54               55
Germany                    13.30       37               44
France                     13.14       51               36
Sweden                     12.76       36               37
Senegal                    12.62       49               51
South Africa               12.15       44               41
South Korea                10.77       59               40

this one shows the number of goals scored based on the preferred_foot. 
it reflects a real-life observation as the number of players with right foot as the prefered foot is larger, the goal corelated are more.

In [62]:
df.groupby("preferred_foot").agg({"goals": "sum", "assists": "sum", "shots_on_target": "sum"}).sort_values(by="goals", ascending=False)

                goals  assists  shots_on_target
preferred_foot
Right            2260     2189             1963
Left              764      670              681